name: CI/CD main for backend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push 
        uses: docker/build-push-action@v4
        with:
          context: ./second-brain-app
          file: ./second-brain-app/Dockerfile
          push: true
          no-cache: true
          tags: msvaibhav4141/brainly-server:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.210.142 -t "docker stop brainlyserver && docker rm brainlyserver &&  docker run -d --name brainlyserver --network brainet -e DB_URL='${{ secrets.DB_URL }}' -e GEMENI_KEY='${{ secrets.GEMENI_KEY }}' -e PINECONE_KEY='${{ secrets.PINECONE_KEY }}' -e HFKEY='${{ secrets.HFKEY }}' -e JWT_SECRET='${{ secrets.JWT_SECRET }}' -e SMTP_PASS='${{ secrets.SMTP_PASS }}' -e SMTP_MAIL='${{ secrets.SMTP_MAIL }}'  -e FRONT_URL='${{ secrets.FRONT_URL }}' -p 3000:3000 msvaibhav4141/brainly-server:${{ github.sha }}"


