name: CI/CD main for backend
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push 
        uses: docker/build-push-action@v4
        with:
          context: ./second-brain-app
          file: ./second-brain-app/Dockerfile
          push: true
          no-cache: true
          tags: msvaibhav4141/brainly-server:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.210.142 -t "docker stop brainlyserver && docker rm brainlyserver &&  docker run -d --name brainlyserver --network brainet -e ${{ secrets.GEMENI_KEY }} -e ${{ secrets.PINECONE_KEY }} -e ${{ secrets.HFKEY }} -e ${{ secrets.JWT_SECRET }} -e ${{ secrets.SMTP_PASS }} -e ${{ secrets.SMTP_MAIL }} -e ${{ secrets.FRONT_URL }} -e ${{ secrets.DB_URL }} -p 3000:3000 msvaibhav4141/brainly-server:${{ github.sha }}"


