name: CI/CD main for backend111111
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and Push 
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./client/second-brain-client/Dockerfile.prod
          build-args:
            - VITE_SERVER_HOST=http://localhost:3000/v1
            - VITE_FRONTEND_URL=http://localhost:5173
          push: true
          tags: msvaibhav4141/brainly-client:${{ github.sha }}
    