name: CI/CD main for client
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client/second-brain-client/
          file: ./client/second-brain-client/Dockerfile.prod
          push: true
          no-cache: true
          build-args: |
              VITE_SERVER_HOST=${{ secrets.VITE_SERVER_HOST }}
              VITE_FRONTEND_URL=${{ secrets.VITE_FRONTEND_URL }}
          tags: msvaibhav4141/brainly-client:${{ github.sha }}
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/.ssh
          chmod 700 /home/runner/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@15.206.210.142 -t "docker stop brainlyclient && docker rm brainlyclient &&  docker run -d --name brainlyclient --network brainet -p 5173:80 msvaibhav4141/brainly-client:${{ github.sha }}"

    