FROM node:24-alpine AS build

ARG VITE_SERVER_HOST
ARG VITE_FRONTEND_URL

ENV VITE_SERVER_HOST=${VITE_SERVER_HOST}
ENV VITE_FRONTEND_UR=${VITE_FRONTEND_URL}

WORKDIR /usr/src/app

COPY package* .

RUN npm install -f

COPY . .

RUN npm run build

FROM nginx:alpine AS prod

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /usr/src/app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


